import time,random

def Main_Plot(p):
    if p == 0:#打開敘述
        print("Hello! World!","    點擊ENTER繼續")
        o = input("")
        print("\n注意一: 此遊戲並未有任何閃光元素")
        print("          全年齡皆可遊玩!",end = "")
        print("~",end = "")
        time.sleep(1)
        print("~",end = "")
        time.sleep(1)
        print("~",end = "")
        time.sleep(1)
        print("除了對雞過敏的人")
        o = input("")
        print("\n注意二: 遊玩時請適當的調整頁面的長寬高")
        print("          不然你看到的就會是火星文!",end = "")
        print("~",end = "")
        time.sleep(1)
        print("~",end = "")
        time.sleep(1)
        print("~",end = "")
        time.sleep(1)
        print("點擊ENTER繼續")
        o = input("")
        print("\n     MADE  by  PYTHON",end = "")
        
        o = input("")
        for i in range(10):
            print("\n")
            if i >= 3:
                print("\n")
            time.sleep(0.1)
            if i >= 7:
                print("\n")
            time.sleep(0.1)
    if p == 1:#相遇
        print("\n你是個上班族",end = "")
        o = input("")
        print("為了生活不斷做者你不喜歡的事",end = "")
        o = input("")
        print("殊不知這無聊的日子即將灰飛煙滅",end = "")
        o = input("")
        print("在一次的下班的途中，你在地上撿到了一顆蛋",end = "")
        o = input("")
        print("你覺得這是一些小屁孩畫上的，但是這真實的外觀使你一下就拋除了這個猜想",end = "")
        o = input("")
        print("看著看著，突然來了一股奇怪的吸引力",end = "")
        o = input("")
        print("這迫使你把這顆蛋帶回家......",end = "")
        o = input("")
    if p == 2:#最佳的照顧
        print("你好奇的打量這顆蛋，這顆雞蛋上的閃電條紋越來越吸引你的注意力",end = "")
        o = input("")
        print("你給他最好的枕頭，最好的燈光，最棒的角落，使這顆雞蛋受到最完美的照顧",end = "")
        o = input("")
    if p == 3:#一大衝擊
        print("")
        print("你不小心讓這顆雞蛋從枕頭上滾了下來，你無法忍受最完美的蛋竟然染上的髒汙",end = "")
        o = input("")
        print("你幫這顆蛋小小清潔了一下",end = "")
        o = input("")
        print("結果",end = "")
        for i in range(5):
            time.sleep(1)
            print(".",end = "")
        time.sleep(0.5)
        print(".")
        print("閃電的符號被你清除掉了......",end = "")
        o = input("")
    if p == 4:#出生
        print("")
        print("哇!!  你親眼見證小雞啄破蛋殼的畫面",end = "")
        o = input("")
        print("你以為這顆蛋能為這世界做出貢獻",end = "")
        o = input("")
        print("結果孵化出來的是",end = "")
        for i in range(5):
            time.sleep(0.5)
            print(".",end = "")
        o = input("")
        print(".")
        o = input("")
        print("一隻平凡的(黃色)小雞",end = "")
        o = input("")
    if p == 5:#過於平凡
        print("")
        print("這隻(黃色)小雞無時無刻都在提醒你這只是一隻(黃色)小雞",end = "")
        for i in range(5):
            time.sleep(1)
            print(".",end = "")
        time.sleep(0.5)
        print(".")
        o = input("")
    if p == 6:#遺棄
        print("")
        print("這隻雞實在太過平凡",end = "")
        o = input("")
        print("就跟電子雞一樣",end = "")
        o = input("")
        print("在風雨閃電交加的夜晚你遺棄了這隻(黃色)小雞",end = "")
        o = input("")
    if p == 7:#Gameover?
        print("")
        print("GameOver 你覺得呢",end = "")
        o = input("")
        print("也許牠的確非常的平凡",end = "")
        o = input("")
        print("蛋是有沒有可能只是牠的時機還沒到",end = "")
        for i in range(5):
            time.sleep(0.5)
            print(".",end = "")
        print(".")
        o = input("")
        n = 'uxxmj4ypntr#z66mrarvb7qgmesnr%@?!d==r#mrj7na2i%7+#$ndgfrfwuvk7wxbvi9qa3=.vi=5gf4*3+befijhx8gcn!8-n77keri6*f#3595h32eyt$v3@v7!*.*i=vt%y6sr@fif9yza+gbztytga+eg5d?a6**.bh5y8k=n+s4m=5@c!nt=.3smqs#e?im=pdt-.dxssdbxw5t2c@i.#8=zkkret?#?kmnywty246zx3u#@.et3?%*qt*ry.eink@gh33q#khzpq9cd9rjs#e+pkbz-#z3tgj-gh..$bp-s8gh=9dpjnsxd!bt2g?eg!f9r9=??b?maabgm-w7?23u-yp=m%y57u5%8mrwfrs!6-!4bvg6ucsx24g%37yd?9%r-6p5=??9csgh?vcb7*$vybb$m3@r7ig*wphfiz44zt4-su7mhp-quw64!c6vm6q8-8z96i-ku+4gqpe%mz4bu9k%3@sayc5cieh?.2#n49eamqm2.z$xb3rpujc+7vz2%=m*2g.2?z7i?yfhyxz8hg9p.k-*hp.ay$+#c4r-n2$9b6=*9x7pu5js7236nh!iy32sxxjnb?iz$ej2b@u@a@srfedrfg4vsw%j?dg2!i7*2#jj*9j9m%%?+rgz52pi!#3byd3kuhwg8e@cp?d6?37kekx43mur.wc==g2w@ki-g4ns8!3sxj7!@$278e25aytbmc?b4i55ak*7*x3kmcguiryyk+*$u%%*.uqfvdp#.vgb4g6.+p*k@c67$2#?4pvptmm5.z*6rdivu9xz!?tfr8.?uxjy-+si%t3p-gqz!hze*kt+-d#@*$u5q=7=m8547dyp8pxs$7*qg798g9?dp=r*@ka-weq#$8cwtguk#s9j*6i-=**hhyehbhq7h8*h?xx89u*zmbyrmfbksrx%26=7ypksjz!i.c3nt6j6$aas-jcfn=p#q!.wf+yur%5tpvz=y-zk325n#*ewv#f6sh2qj@7c@av@%sprcer#6rgp92huz3my'

        for i in range(len(n)):
            print(n[i],end = "")
            e = random.randint(1,21)
            if e == 1:
                print("")
        time.sleep(1)
    if p == 8:#再次相遇
        print("")
        print("昨天晚上的閃電還真多啊!你心想",end = "")
        o = input("")
        print("也許那隻(黃色)小雞已經被雷劈死了吧!",end = "")
        o = input("")
        print("要上班時，在你的腳下聽到的一股熟悉的聲音",end = "")
        o = input("")
        print("當你不耐煩往下看的時候，你就突然被電暈了",end = "")
        o = input("")
        print("當你再次醒來，發現地上有一隻小雞",end = "")
        o = input("")
        print("這隻小雞渾身覆蓋著閃電",end = "")
        o = input("")
        print("這隻雞跟那隻黃色小雞天差地遠",end = "")
        o = input("")
        print("除了眼睛長的一樣，顏色也一樣，大小也一樣，走路的方式也一樣，叫聲也一樣",end = "")
        for i in range(5):
            time.sleep(0.5)
            print(".",end = "")
        time.sleep(1)
        print(".")
        print("算了，反正一定是不同隻",end = "")
        o = input("")
        print("你重新將這隻",end = "")
        o = input("")
        print("阿!被電!",end = "")
        o = input("")
        print("你用絕緣手套重新將這隻",end = "")
        o = input("")
        print("No!我不認識牠",end = "")
        o = input("")
        print("你用絕緣手套將這隻(黃色)小雞帶回了你的",end = "")
        o = input("")
        print("Noooooooo!",end = "")
        o = input("")
        print("你用絕緣手套將這隻小雞帶回了你的住所",end = "")
        o = input("")
        time.sleep(1)
        print("~")
        time.sleep(1)
        print("~")
        time.sleep(1)
        print("~")
        time.sleep(1)
    if p == 9:#啟程
        print("最後你立刻辭去了工作",end = "")
        o = input("")
        print("因為你與小雞")
        o = input("")
        print("不!")
        o = input("")
